export const  ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const  ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const  ORDER_CREATE_FAILD = "ORDER_CREATE_FAILD"
export const  ORDER_CREATE_RESET = "ORDER_CREATE_RESET"